### ISSUE TITLE
No serviço de sugestão de eventos ocorre erro no cadastramento após o dia 12

### ISSUE THREAD

**Issue by marcoslmori** [bireme/direve-wp-plugin#1]
URL testada: http://bvsalud.org/direve/suggest-event/  na instância em Portugues. 

Quando você cadastra no campo de dia  um número superior ao numero 12  ocorre o erro que não permite ir adiante.  

![image](https://cloud.githubusercontent.com/assets/10047460/8939030/87a1d430-3538-11e5-8ac8-8efe8bcf8bea.png)

**Comment by marcoslmori** [comment]
Foi usado o navegador chrome Versão 44.0.2403.107 m em portugues.

**Comment by viniciusandrade** [comment]
Ajuste realizado no fi-admin https://github.com/bireme/fi-admin/commit/b68000e2db89a55b6e8e8885af15288ffdd68805
