### ISSUE TITLE
Criar nova opção de página inicial do plug-in

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/direve-wp-plugin#11]
Fazer com que o plug-in permita que o web master defina a arquitetura da página inicial:

- Usar a página atual (lista dos atos normativos + clusters)
- Usar página com um mosaico de cards (clusters)

Relacionado ao issue bireme/leisref-wp-plugin#17

**Comment by suelisuga** [comment]
Sugiro benchmark com: https://www.even3.com.br/eventos-online/medicina/

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Segue imagem do novo formato de layout da página inicial:

![screenshot-localhost-2023 07 04-14_38_21](https://github.com/bireme/direve-wp-plugin/assets/3779520/9f204a6e-346d-4267-845d-cae926f88376)

**Comment by suelisuga** [comment]
@wilsonmoura vc é show!! ;-)

Seria possível separar modalidades de eventos (virtual - pode ser eventos do dia); híbrido e presencial (agora não sei bem o prazo melhor, mas se vermos o resultado, será que não seria com pelo menos 2 meses de antecedência?)

Há dois outros clusters que penso que fazem falta (área temática e Ano e mês do evento). Para ambos já existem chamados abertos.

Pergunta: para eu visualizar tenho que pedir para o Mori atualizar a instancia de teste? Seria posível incluir imagens padrão nos assuntos?

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga seguem alguns comentários:

- Seria possível separar modalidades de eventos (virtual - pode ser eventos do dia); híbrido e presencial (agora não sei bem o prazo melhor, mas se vermos o resultado, será que não seria com pelo menos 2 meses de antecedência?)
  - **Para exibir novas áreas para cada modalidade, será necessário aumentar o número de requisições das APIs disponíveis no FI-ADMIN e, por conseguinte, gerando mais consumo dos serviços disponíveis atualmente. Sendo assim, a recomendação é evitar esse tipo de implementação, visando manter os serviços funcionando com normalidade.**
- Há dois outros clusters que penso que fazem falta (área temática e Ano e mês do evento). Para ambos já existem chamados abertos.
  - As análises de implementação dessas atividades serão feitas nos respectivos issues registrados no GitHub.
- Pergunta: Para eu visualizar, tenho que pedir para o Mori atualizar a instancia de teste? Seria possível incluir imagens padrão nos assuntos?
  - Para as atualizações em ambiente de testes, podemos realizar esse tipo de atividade. Com relação ás imagens, elas teriam que ser inseridas no sistema de origem (FI-ADMIN) em cada evento registrado, para que depois houvesse a possibilidade de exibir as imagens no plugin.

**Comment by suelisuga** [comment]
@wilsonmoura espia a proposta

Página inicial:
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/bfcd893a-84ca-4d1c-b36c-fb939b8898ae)
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/bcbeb37d-667f-4d54-818c-bec11fe2abe5)


Lista de registros (ao lado inclui a lista de clusters):
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/20976509-3380-44ac-957c-fbe9abef2f91)


Formato detalhado:
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/efb6bbf9-9b9d-47fe-8a3d-d614508cf902)

Acredito que faltou a proposta para o Ver mais, pois atualmente a lista dos itens do cluster não é completa. Há uma limitação de mostrar 20 itens e os outros não são mostrados.

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga fizemos alguns ajustes.Segue alguns comentários:

- No carrossel de eventos, aumentamos o número de eventos para 20 cards para atender também a necessidade de exibir eventos mais distantes.
- Agora também é possível visualizar a informação do campo Modalidade do Evento.
- Com relação aos filtros, vamos incluir aos poucos seguindo o planejamento de atualização dos plugins.

Vale ressaltar que a estrutura de layout sugerida já está implementada. Sendo assim, podemos encerrar essa atividade?
