### ISSUE TITLE
Incluir no formato detalhado a informação contida no campo "Observações"

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#17]
Prezados,

Solicito que sempre que o campo "Observações" for preenchido, essa informação seja apresentada ao usuário final.

Atualmente os CC estão incluindo informações no campo "Informações de contato" para que sejam visualizados pelo usuário final.
![image](https://user-images.githubusercontent.com/13105683/59385030-e2d87680-8d39-11e9-8e1a-6d3009e20238.png)

Caso reportado por e-mail.

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga implementado em #2``
