### ISSUE TITLE
Incluir no formato detalhado a informação contida no campo "Público Alvo"

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#18]
Prezados,

Solicito que sempre que o campo "Público alvo" for preenchido, essa informação seja apresentada ao usuário final.

Atualmente os CC estão incluindo informações no campo "Informações de contato" para que sejam visualizados pelo usuário final.

![image](https://user-images.githubusercontent.com/13105683/59385170-27641200-8d3a-11e9-8295-a08791dda94a.png)
Caso reportado por e-mail.

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga implementado em #2
