### ISSUE TITLE
Incluir total de registros no plug-in DirEve para facilitar gestão da fonte

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#19]
Prezados,

Coordenadora de BVS necessita visualizar de número total de registros de eventos de forma mais facilitada.

Solicito inclusão do total conforme imagem:
![image](https://user-images.githubusercontent.com/13105683/59385757-70689600-8d3b-11e9-96fa-23fa504ede0b.png)

Muito obrigada!
Sueli

**Comment by marcoslmori** [comment]
o total de eventos deve aparece na pagina inicial, independente de clicar em  [Ver todos os eventos]

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor atualizar o plugin no respectivo site e validar.
