### ISSUE TITLE
Plugin do DirEve não apresenta informação inserida no FI-Admin no formato detalhado [ocomon 4299]

### ISSUE THREAD

**Issue by marcoslmori** [bireme/direve-wp-plugin#2]
Demanda recebida via ocomon da sueli:

-----------------------------------------
Prezados,

Plugin do DirEve não apresenta informação inserida no FI-Admin no formato detalhado.

Inserir no formato detalhado:
-Idiomas oficiais do evento
-E-mail para contato 
-Observações
-Publico alvo

Obrigada
Sueli

**Comment by suelisuga** [comment]
Relacionado com #18 e #17

**Comment by wilsonmoura** [comment]
Relacionado com bireme/fi-admin#1412

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor validar.

**Comment by suelisuga** [comment]
@wilsonmoura 
Tradução dos campos nos 3 idiomas (PT | EN | ES):
-Idiomas oficiais do evento | Official languages | Idiomas oficiales 
-Contato | Contact | Contacto
-Observações | Observations | Observaciones
-Publico alvo | Target audience | Audiencia
-Modalidade do Evento | Event modality | Modalidad del Evento

Poderia revisar segundo os campos:

**Observações:**
é possível apresentar conforme está no FI-Admin, ou seja, com Enter e espaço?

![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/584065e5-e083-449a-b617-115fd0232f53)

No FI-Admin:
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/d8fa711c-ad9b-4602-bdb8-066901f5024d)

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados na formatação do campo. Favor solicitar atualização do plugin novamente e validar.

**Comment by suelisuga** [comment]
@marcoslmori vc pode atualizar a instancia de teste da bvs brasil para eu revisar? Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga plugin atualizado conforme solicitado.

**Comment by suelisuga** [comment]
@wilsonmoura só não encontrei Modalidade do Evento | Event modality | Modalidad del Evento. Será que preciso pedir nova atualização para o @marcoslmori ?

**Comment by wilsonmoura** [comment]
@suelisuga o campo Modalidade do Evento aparece no começo do bloco de informações sobre o evento (ver imagem):

![screenshot-localhost-2023 07 07-03_52_50](https://github.com/bireme/direve-wp-plugin/assets/3779520/d488d3b4-46e8-477f-b163-350fad53f45b)

**Comment by suelisuga** [comment]
Validado! Obrigada @wilsonmoura
