### ISSUE TITLE
Melhorar a visibilidade do "Ver todos os eventos" - incluir no topo da página

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#20]
Prezados,

Solicito mudança da localização do "Ver todos os eventos" no plug-in DirEve para melhorar a visibilidade desse item, pois atualmente está escondido na parte inferior à esquerda.

Sugiro no topo à direita.

![image](https://user-images.githubusercontent.com/13105683/59386075-2c29c580-8d3c-11e9-89c4-8d2a3ddd13ef.png)

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.

**Comment by wilsonmoura** [comment]
@suelisuga esse ajuste foi realizado apenas no layout padrão. Sendo assim, para que possa validar, ajustamos as configurações do DirEve da BVS Brasil para assumir o layout padrão.
