### ISSUE TITLE
Erro quando o usuário sugere um novo evento

### ISSUE THREAD

**Issue by marcoslmori** [bireme/direve-wp-plugin#27]
Quando no plugin do direve, no caso, bvsalud.org, u usuário faz alguma sugestão de eventos, ocorre esse erro: https://fi-admin.data.bvsalud.org/suggest-event  --> The requested URL /suggest-event was not found on this server.

**Comment by marcoslmori** [comment]
alguma novidade sobre esse issue?

**Comment by viniciusandrade** [comment]
@marcoslmori ajuste realizado no plugin, favor atualizar o plugin na instância bvsalud.org.

**Comment by viniciusandrade** [comment]
@marcoslmori aberto chamado Ocomon 7584 para finalizar por aqui.
