### ISSUE TITLE
Erro na solicitação de sugestão de eventos [Caso MTCI]

### ISSUE THREAD

**Issue by marcoslmori** [bireme/direve-wp-plugin#29]
Mesmo depois de atualizar o plugin o erro permaneceu.   Veja mensagem de erro na imagem abaixo:  

link:  
Inicial --> https://mtci.bvsalud.org/eventos/suggest-event/
Serviço --> https://fi-admin.bvsalud.org/suggest-event

![image](https://user-images.githubusercontent.com/10047460/136563895-bee0d678-1563-4883-ac3a-967c63ce9503.png)

**Comment by sousajul** [comment]
Alguma novidade nesse issue? Também ocorreu na BVS Costa Rica https://costarica.teste.bvsalud.org/.

https://costarica.teste.bvsalud.org/direve/suggest-event/
![ERROR 1](https://user-images.githubusercontent.com/13439949/137784023-26ea4754-89fc-4036-8e02-4e5cd94b33b0.jpg)
![INGRESO EVENTO](https://user-images.githubusercontent.com/13439949/137784035-bbcc4d9a-e7d8-492f-b567-8cf1df1cd4ac.jpg)

**Comment by viniciusandrade** [comment]
@marcoslmori erro corrigido para a instância MTCI, para demais instâncias é necessário que o plugin esteja atualizado com a mesma versão do MTCI.

Favor proceder com atualização para instância Costa Rica e solicitar a validação da @sousajul.

Obrigado

**Comment by viniciusandrade** [comment]
Fechado issue pela resolução do erro no plugin, aguardando atualização na instância da Costa Rica.
