### ISSUE TITLE
Plugin do DirEve não funciona com o enlace permanente "Nome da Entrada" 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/direve-wp-plugin#3]
Caso: mtci.bvsalud.org

Configuração do enlace permanente:  Nome da Entrada
Configuração do Plugin:  Página do Plugin: direve
Acesso ao plugin: http://mtci.hom.bvsalud.org/direve/
Erro: 
"This is somewhat embarrassing, isn’t it?
It seems we can’t find what you’re looking for. Perhaps searching can help."

Ao mudar a configuração do enlace permanente para "dia e nome" funciona corretamente.

**Comment by viniciusandrade** [comment]
@marcoslmori 

Ajuste realizado no plugin. Por favor atualizar na instância e realizar novo teste. Obrigado.

**Comment by marcoslmori** [comment]
validado
