### ISSUE TITLE
Criar cluster de Área Temática

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#31]
Solicito criar cluster de Área Temática (até 20 opções e incluir opção Ver todas)

Muito obrigada
Sueli

Relacionado https://github.com/bireme/lis-wp-plugin/issues/19

**Comment by wilsonmoura** [comment]
@suelisuga o filtro por área temática foi implementado conforme solicitado. Favor validar.

**Comment by suelisuga** [comment]
@wilsonmoura cluster implantado com sucesso!
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/be82d187-2c53-4d37-a92e-9353bea431f8)


Solicito item "Ver mais" pois há hoje 128 áreas temáticas criadas.

![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/e56234ad-f873-462b-92ba-6ae87eb2dac2)


Obrigada!

**Comment by suelisuga** [comment]
Implantação ok. Chamado relacionado #40 para seguimento da atividade.

Muito obrigada!
