### ISSUE TITLE
RSS do direve apresenta mensagem de erro quando não há eventos futuros cadastrados

### ISSUE THREAD

**Issue by barrosjo** [bireme/direve-wp-plugin#33]
![image](https://user-images.githubusercontent.com/19578003/206012126-8af69e38-ff88-4702-88b8-9e4cbf4455c9.png)
Sugestão de texto para quando não houver eventos futuros: Não há eventos futuros

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados. Favor solicitar atualização do plugin no respectivo site e validar.
