### ISSUE TITLE
Incluir filtro de ano e mês de publicação com quantidade de registros

### ISSUE THREAD

**Issue by marcoslmori** [bireme/direve-wp-plugin#36]
Facilita a recuperação para o usuário final o evento desejado 

Comportamento desejável: clicar no ano, e dar a opção de escolher o mês. 

Exemplo:
2023 (10) + abre os meses, em ordem cronológica decrescente.  
 05/23 (2)
 04/23 (3)

**Comment by wilsonmoura** [comment]
@marcoslmori no plugin DirEve, já existe um filtro por ano/mês/dia no formato de calendário (ver imagem). Sendo assim, favor confirmar se essa demanda realmente é necessária.

![screenshot-bvsalud org-2023 05 16-01_18_37](https://github.com/bireme/direve-wp-plugin/assets/3779520/ed3b4d20-ecde-4e2d-9bb8-152ad8c7364a)

**Comment by wilsonmoura** [comment]
@marcoslmori no plugin DirEve, já existe um filtro por mês/dia no formato de calendário (ver imagem). Talvez ajustar esse widget para exibir um filtro por ano possa resolver essa necessidade. Sendo assim, favor confirmar se essa demanda realmente é necessária, pois o ideal seria reaproveitar esse filtro por data já existente.

![screenshot-bvsalud org-2023 05 16-01_18_37](https://github.com/bireme/direve-wp-plugin/assets/3779520/ed3b4d20-ecde-4e2d-9bb8-152ad8c7364a)

**Comment by suelisuga** [comment]
@wilsonmoura embora exista essa funcionalidade, ela não é de tão fácil visualização dos próximos eventos se eles forem mais distantes.
Penso que seria fundamental incluir esse cluster para facilitar a navegação por parte do usuário.
Muito obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga o filtro por ano foi implementado conforme solicitado. Favor validar.

**Comment by suelisuga** [comment]
@wilsonmoura o filtro aparece, porém eventos de 2023 não foram contabilizados.
Poderia verificar?

Outro ponto é que o label poderia ser "Ano do evento" e não "Ano de publicação", pois esse label é mais para publicações tradicionais.

![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/3a1b65eb-0f75-4f1b-ad1b-208137eaee13)

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados no nome do filtro conforme solicitado. Com relação aos eventos do ano de 2023, provavelmente existem poucos eventos cadastrados nesse ano. Por isso essa opção de filtro ainda não está disponível na lista atual.

**Comment by suelisuga** [comment]
Estrategia para recuperar registros de 2023: https://bvsalud.org/direve/?q=start_date%3A%5B2023-1-1T00%3A00%3A00Z+TO+2023-12-31T00%3A00%3A00Z%5D
