### ISSUE TITLE
Funcionalidade "Ver mais" nos clusters

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#40]
Solicito que todos os clusters do Diretório de Eventos tenham a opção "Ver mais", pois causa a falsa impressão de termos só 20 opções em cada cluster, sendo que há centenas de opções para cada um deles. Implantações realizadas nos chamados #31 e #36 estão ok, porém causa confusão porque no caso do ano do evento, não apareceram os registros de 2023.

Muito obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar
