### ISSUE TITLE
Link de evento ultrapassa limite do registro

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#43]
Verifiquei que o link do evento está ultrapassando o espaço definido para metadados do evento: id 27539
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/ce5b273d-1e3b-47a0-bdbe-93ed96648c9c)

Obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados. Favor validar.

**Comment by suelisuga** [comment]
Link está funcionando, mas aparece somente parte do link.

![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/018795df-2352-4e0c-b449-3cb20bd09753)

Se essa era a implantação, está ok.

Se a intenção era manter link inteiro, parte da visualização estão faltando.

Obrigada
