### ISSUE TITLE
Evento marcado como pendente está aparecendo na interface Publica

### ISSUE THREAD

**Issue by sousajul** [bireme/direve-wp-plugin#5]
O evento ID 23502 - 62ª Congresso Brasileiro de Oftalmologia (05/09/2018 - 08/09/2018. Maceió - Brasil) está marcado como "pendente" para a área temática Medicinas Tradicionales, Complementarias e Integrativas, no entanto, aparece na interface publica da BVS no RSS e no plugin do Direve.

![plugin-direve-bvs mtci](https://user-images.githubusercontent.com/13439949/40236802-11f20186-5a85-11e8-9174-7d40f8942976.png)

**Comment by viniciusandrade** [comment]
Após correções aplicadas no passado não se observa mais este comportamento no sistema. Caso ocorra novamente favor re-abrir o issue.
