### ISSUE TITLE
Direve Regional não altera as interfaces dos idiomas

### ISSUE THREAD

**Issue by sousajul** [bireme/direve-wp-plugin#7]
O Direve Regional não está alterando a interface de acordo com o idioma selecionado.

**Comment by marcoslmori** [comment]
Relacionado com issue #8

**Comment by wilsonmoura** [comment]
@sousajul ajustes realizados. Favor validar no ambiente de testes do Portal Regional: https://teste.bvsalud.org/direve

**Comment by sousajul** [comment]
@wilsonmoura validado.
