### ISSUE TITLE
Plugin do Direve não apresenta as opções de idiomas na BVS MTCI

### ISSUE THREAD

**Issue by sousajul** [bireme/direve-wp-plugin#8]
Plugin do Direve não apresenta as opções de idiomas na BVS MTCI embora a BVS esteja em 3 idiomas.  http://mtci.bvsalud.org/.

**Comment by marcoslmori** [comment]
Desenvolver o template do header customizado para o plugin direve funcionar para os idiomas

**Comment by suelisuga** [comment]
Relacionado #7

**Comment by marcoslmori** [comment]
Problema reportado no issue #7

**Comment by sousajul** [comment]
Não entendi a solução. O direve do MTCI continua sem as opções de idiomas. Favor verificar novamente.

**Comment by wilsonmoura** [comment]
@sousajul ajustes realizados em #7. Favor validar no ambiente de testes da BVS MTCI.

**Comment by sousajul** [comment]
@wilsonmoura validado, necessário fazer ajustes de CSS.
