### ISSUE TITLE
Ex-descritores DeCS aparecem com código de ID do antigo descritor

### ISSUE THREAD

**Issue by suelisuga** [bireme/direve-wp-plugin#9]
Descritores DeCS frequentemente mudam de status de autorizado para sinônimos ou histórico.
O descritor "Bibliotecas Virtuais" tornou-se sinônimo de "Bibliotecas Digitais" e agora todo registro no qual foi utilizado o primeiro descritor, aparece com o número 50119.

Identifiquei esse problema sempre que há mudança no descritor e consegui identificar esse erro nos  plug-ins:

DirEve:
![image](https://user-images.githubusercontent.com/13105683/42093437-abe785e0-7b82-11e8-966c-1be7d42b408f.png)

Multimedia:
![image](https://user-images.githubusercontent.com/13105683/42093630-637519ac-7b83-11e8-9053-5004204729dd.png)

Obrigada!
Sueli

**Comment by suelisuga** [comment]
Chamado aberto também em: https://github.com/bireme/fi-multimedia-wp-plugin/issues/6

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados no plugin DirEve. Favor validar no Portal Regional: https://bvsalud.org/direve

**Comment by suelisuga** [comment]
@wilsonmoura notei que os códigos dos descritores não aparecem, mas também não aparece o texto do descritor.

Gostaria de esclarecimento de qual foi a solução encontrada. Em princípio seria importante termos como recuperar os eventos indexados sob o descritor que foi substituido, incluindo um novo descritor.

Testei e não encontrei um descritor correspondente.

Exemplo: 50230 - 1287 ocorrências
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/723d1aba-2409-4d00-b017-96fb3836b3cc)

Aqui não há um texto ou um redirecionamento do descritor
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/8651659f-0073-4efb-a7a3-7db3fd3e607b)

No caso do id 52503 - 381 registros
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/3d855c0a-d412-4d66-b1a0-bd4eb1f088c0)

Os registros não foram apresentados:
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/739d0e84-b7d6-4f0b-a71a-9e21d3cf411b)

É possível sabermos quais foram os eventos (registros) que haviam sido indexados sob o descritor excluido/atualizado?
![image](https://github.com/bireme/direve-wp-plugin/assets/13105683/aa1506f7-a014-4ddf-8fd9-2aa9d1bca394)

Muito obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga quando ocorre esse tipo de comportamento, significa que são IDs de termos autorizados que se tornam termos alternativos ou que são excluídos ou apagados. Sendo assim, devem ser ignorados para normalizar o cluster Assunto. No entanto, isso não resolve a origem do problema, que envolve o índice de pesquisa utilizado no plugin. Mas vale reforçar que esse ajuste foi apenas garantir o comportamento adequado do plugin DirEve.

Existe um issue para tratar desse tema específico do índice de pesquisa: bireme/Gestao-DeCS#58
